In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [9]:
df = pd.read_csv('/content/training.1600000.processed.noemoticon.csv.zip', encoding= 'latin-1', header=None)
df = df[[0,5]]
df.columns = ['polarity', 'text']
df.head()

   polarity                                               text
0         0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1         0  is upset that he can't update his Facebook by ...
2         0  @Kenichan I dived many times for the ball. Man...
3         0    my whole body feels itchy and like its on fire
4         0  @nationwideclass no, it's not behaving at all....

In [10]:
df['polarity']= df['polarity'].map({0:0, 4:1})
df.head()

   polarity                                               text
0         0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1         0  is upset that he can't update his Facebook by ...
2         0  @Kenichan I dived many times for the ball. Man...
3         0    my whole body feels itchy and like its on fire
4         0  @nationwideclass no, it's not behaving at all....

In [11]:
df.isnull().sum()

polarity    0
text        0
dtype: int64

In [12]:
def clean_text(text):
  text = text.lower()
  return text
df['text']= df['text'].apply(clean_text)
df.head()

   polarity                                               text
0         0  @switchfoot http://twitpic.com/2y1zl - awww, t...
1         0  is upset that he can't update his facebook by ...
2         0  @kenichan i dived many times for the ball. man...
3         0    my whole body feels itchy and like its on fire
4         0  @nationwideclass no, it's not behaving at all....

In [13]:
x = df['text']
y= df['polarity']
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state= 42, test_size= 0.2)

In [14]:
vectorizer = TfidfVectorizer(max_features = 5000, ngram_range= (1,2))
x_train_vectorizer = vectorizer.fit_transform(x_train)
x_test_vectorizer = vectorizer.fit_transform(x_test)

In [15]:
bnb = BernoulliNB()
bnb.fit(x_train_vectorizer, y_train)
bnb_pred = bnb.predict(x_test_vectorizer)
print("bernoulliNB accuracy score",accuracy_score(y_test, bnb_pred))
print("bernoulliNB classification report", classification_report(y_test, bnb_pred))
print("bernoulliNB conlusion score ", confusion_matrix(y_test, bnb_pred))

bernoulliNB accuracy score 0.623865625
bernoulliNB classification report               precision    recall  f1-score   support

           0       0.63      0.61      0.62    159494
           1       0.62      0.64      0.63    160506

    accuracy                           0.62    320000
   macro avg       0.62      0.62      0.62    320000
weighted avg       0.62      0.62      0.62    320000

bernoulliNB conlusion score  [[ 97612  61882]
 [ 58481 102025]]

In [16]:
svm = LinearSVC(max_iter=1000)
svm.fit(x_train_vectorizer, y_train)
svm_pred = svm.predict(x_test_vectorizer)
print("Svm accuracy score",accuracy_score(y_test, svm_pred))
print("Svm classification report", classification_report(y_test, svm_pred))
print("Svm conlusion score ", confusion_matrix(y_test, svm_pred))

Svm accuracy score 0.571696875
Svm classification report               precision    recall  f1-score   support

           0       0.57      0.61      0.59    159494
           1       0.58      0.54      0.56    160506

    accuracy                           0.57    320000
   macro avg       0.57      0.57      0.57    320000
weighted avg       0.57      0.57      0.57    320000

Svm conlusion score  [[97035 62459]
 [74598 85908]]

In [17]:
Logrex = LogisticRegression(max_iter= 100)
Logrex.fit(x_train_vectorizer, y_train)
logrex_pred = Logrex.predict(x_test_vectorizer)
print("LogisticRegression accuracy score",accuracy_score(y_test, logrex_pred))
print("LogisticRegression classification report", classification_report(y_test, logrex_pred))
print("LogisticsRegresiion conlusion score ", confusion_matrix(y_test, logrex_pred))

LogisticRegression accuracy score 0.57491875
LogisticRegression classification report               precision    recall  f1-score   support

           0       0.57      0.57      0.57    159494
           1       0.58      0.58      0.58    160506

    accuracy                           0.57    320000
   macro avg       0.57      0.57      0.57    320000
weighted avg       0.57      0.57      0.57    320000

LogisticsRegresiion conlusion score  [[91324 68170]
 [67856 92650]]

In [47]:
sample_tweets =[""]
sample_vec = vectorizer.transform(sample_tweets)
print(bnb.predict(sample_vec))
print(svm.predict(sample_vec))
print(Logrex.predict(sample_vec))

#negative tweets examples
#@Company, waited 45 minutes and my food is cold. Terrible service."
# "This new policy is an absolute disaster and will ruin everything."
#Chadwick Boseman, announcing his death from cancer,

#positive tweets examples
#"The only way to do great work is to love what you do."
#"Wishing you a productive and peaceful day
#"Congratulations to the Astronauts that left Earth today. Good choice"

[1]
[1]
[1]